// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMd7FqBWvVfGoF51TkCqoSkLkSjLmFF6E',
    appId: '1:659440290874:web:109347708d368ff3b93903',
    messagingSenderId: '659440290874',
    projectId: 'todo-list-mobile-project',
    authDomain: 'todo-list-mobile-project.firebaseapp.com',
    storageBucket: 'todo-list-mobile-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkctGeQqk88D5CsNo-QF9m9ReqD726Z0w',
    appId: '1:659440290874:android:6986bc2f98f9e5a3b93903',
    messagingSenderId: '659440290874',
    projectId: 'todo-list-mobile-project',
    storageBucket: 'todo-list-mobile-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8ePNhviOh6qYtzkk8ouwnAoKiDIYE-5k',
    appId: '1:659440290874:ios:f1e36e596e2c1347b93903',
    messagingSenderId: '659440290874',
    projectId: 'todo-list-mobile-project',
    storageBucket: 'todo-list-mobile-project.appspot.com',
    iosClientId: '659440290874-u3s1p113gtitpfa09md2pjli3vb4guuq.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8ePNhviOh6qYtzkk8ouwnAoKiDIYE-5k',
    appId: '1:659440290874:ios:f1e36e596e2c1347b93903',
    messagingSenderId: '659440290874',
    projectId: 'todo-list-mobile-project',
    storageBucket: 'todo-list-mobile-project.appspot.com',
    iosClientId: '659440290874-u3s1p113gtitpfa09md2pjli3vb4guuq.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoList',
  );
}
